BEGIN;
DROP TABLE IF EXISTS FAT_PROFESSOR_PNP;
CREATE TABLE FAT_PROFESSOR_PNP
(
    FAT_PRO_ID integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    FAT_PRO_RSC character varying,
    FAT_PRO_CARREIRA character varying,
    FAT_PRO_CONTRATO character varying,
    DIM_UNI_ID integer NOT NULL,
    DIM_TIT_ID integer NOT NULL,
    DIM_JOR_ID integer NOT NULL,
    DIM_TEM_ID integer NOT NULL,
    FAT_QUANTIDADE integer NOT NULL DEFAULT 1
);
COMMENT ON TABLE FAT_PROFESSOR_PNP
    IS 'Fonte de dados:microdados PNP - servidores 2021.';
   
DROP TABLE IF EXISTS FAT_TECNICO_PNP;
CREATE TABLE FAT_TECNICO_PNP
(
    FAT_TEC_ID integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    FAT_TEC_CLASSE character varying,
    FAT_TEC_CONTRATO character varying,
    DIM_UNI_ID integer NOT NULL,
    DIM_TIT_ID integer NOT NULL,
    DIM_JOR_ID integer NOT NULL,
    DIM_TEM_ID integer NOT NULL,
    FAT_QUANTIDADE integer NOT NULL DEFAULT 1,
    PRIMARY KEY (FAT_TEC_ID)
);
COMMENT ON TABLE FAT_TECNICO_PNP
    IS 'Origem dos dados: microdados_servidores PNP 2021.';
   
DROP TABLE IF EXISTS DIM_UNIDADE;
CREATE TABLE DIM_UNIDADE
(
    DIM_UNI_ID integer NOT NULL,
    DIM_UNI_INSTITUICAO character varying,
    DIM_UNI_REGIAO character varying,
    DIM_UNI_UF character(2),
    DIM_UNI_UNIDADE character varying,
    PRIMARY KEY (DIM_UNI_ID)
);
COMMENT ON TABLE DIM_UNIDADE
    IS 'Origem dos dados: microdados_servidores PNP 2021.';
COMMENT ON COLUMN DIM_UNIDADE.DIM_UNI_INSTITUICAO
    IS 'InstituiÃ§Ã£o';
COMMENT ON COLUMN DIM_UNIDADE.DIM_UNI_REGIAO
    IS 'RegiÃ£o';
COMMENT ON COLUMN DIM_UNIDADE.DIM_UNI_UF
    IS 'UF';
COMMENT ON COLUMN DIM_UNIDADE.DIM_UNI_UNIDADE
    IS 'Unidade de Ensino';
   
DROP TABLE IF EXISTS DIM_TITULACAO;
CREATE TABLE DIM_TITULACAO
(
    DIM_TIT_ID integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    DIM_TIT_TITULACAO character varying,
    PRIMARY KEY (DIM_TIT_ID)
);
COMMENT ON TABLE DIM_TITULACAO
    IS 'Origem dos dados: microdados_servidores PNP 2021.';
COMMENT ON COLUMN DIM_TITULACAO.DIM_TIT_TITULACAO
    IS 'TitulaÃ§Ã£o';
   
DROP TABLE IF EXISTS DIM_JORNADA_TRABALHO;
CREATE TABLE DIM_JORNADA_TRABALHO
(
    DIM_JOR_ID integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    DIM_JOR_JORNADA character varying,
    PRIMARY KEY (DIM_JOR_ID)
);
COMMENT ON TABLE DIM_JORNADA_TRABALHO
    IS 'Fonte de dados:microdados PNP - servidores 2021.';
COMMENT ON COLUMN DIM_JORNADA_TRABALHO.DIM_JOR_JORNADA
    IS 'Jornada de trabalho';
DROP TABLE IF EXISTS DIM_TEMPO;
CREATE TABLE DIM_TEMPO
(
    DIM_TEM_ID integer NOT NULL,
    DIM_TEM_ANO integer,
    PRIMARY KEY (DIM_TEM_ID)
);
COMMENT ON TABLE DIM_TEMPO
    IS 'DimensÃ£o adicional DW.';
COMMENT ON COLUMN DIM_TEMPO.DIM_TEM_ANO
    IS 'Ano relativo aos dados.';
ALTER TABLE IF EXISTS FAT_PROFESSOR_PNP
    ADD FOREIGN KEY (DIM_UNI_ID)
    REFERENCES DIM_UNIDADE (DIM_UNI_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS FAT_PROFESSOR_PNP
    ADD FOREIGN KEY (DIM_TIT_ID)
    REFERENCES DIM_TITULACAO (DIM_TIT_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS FAT_PROFESSOR_PNP
    ADD FOREIGN KEY (DIM_JOR_ID)
    REFERENCES DIM_JORNADA_TRABALHO (DIM_JOR_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS FAT_PROFESSOR_PNP
    ADD FOREIGN KEY (DIM_TEM_ID)
    REFERENCES DIM_TEMPO (DIM_TEM_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS FAT_TECNICO_PNP
    ADD FOREIGN KEY (DIM_UNI_ID)
    REFERENCES DIM_UNIDADE (DIM_UNI_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS FAT_TECNICO_PNP
    ADD FOREIGN KEY (DIM_TIT_ID)
    REFERENCES DIM_TITULACAO (DIM_TIT_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS FAT_TECNICO_PNP
    ADD FOREIGN KEY (DIM_JOR_ID)
    REFERENCES DIM_JORNADA_TRABALHO (DIM_JOR_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE IF EXISTS FAT_TECNICO_PNP
    ADD FOREIGN KEY (DIM_TEM_ID)
    REFERENCES DIM_TEMPO (DIM_TEM_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
INSERT INTO DIM_TEMPO(DIM_TEM_ID ,DIM_TEM_ANO) values (1,2021);
END;